version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:&PORT && gunicorn mysite.wsgi:application --bind 0.0.0.0:$PORT
    ports:
      - "${PORT}:${PORT}" # miesto 8001 dat kvoli Render $PORT
  
    env_file:
      - .env  # Use .env file
    depends_on:
      - db
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DEBUG=False
      - DJANGO_DB_HOST=db
      - PORT=8001  # This will be overridden by Render
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # uchova to data
    networks:
      - backend

  db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # uchova data
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/code/static  # pridane kvoli statickym suborom
    networks:
      - backend    

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:

