# Generated by Django 3.2.25 on 2024-05-12 06:34
import os
from django.db import migrations
from django.contrib.auth.models import User


def generate_superuser(apps, schema_editor):
    DJANGO_SU_NAME = os.environ.get('DJANGO_SU_NAME')
    DJANGO_SU_EMAIL = os.environ.get('DJANGO_SU_EMAIL')
    DJANGO_SU_PASSWORD = os.environ.get('DJANGO_SU_PASSWORD')

    superuser = User.objects.create_superuser(
        username='admin',
        email='info@comto.sk',
        password='admin')
    superuser.save()
                            # DJANGO_SU_NAME,
                             # DJANGO_SU_EMAIL
                              # DJANGO_SU_PASSWORD

class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(generate_superuser),
    ]
